### PR TITLE
access-om3-nuopc: depend on esmf with -fp-model precise

### PR DESCRIPTION
**Pull request by harshula**
* Also, use when="%intel"

### CODE REVIEW

**Comment by harshula** [comment]
Hi @anton-seaice , You can put your notes from testing, here.

**Comment by harshula** [comment]
Fixes: https://github.com/ACCESS-NRI/ACCESS-OM3/issues/9

**Review by micaeljtoliveira — APPROVED** [review]
LGTM

**Comment by anton-seaice** [comment]
I built access-om3 using this spack-packages and the ACCESS-OM3 environment @ 3-spack-yaml-versioning (https://github.com/ACCESS-NRI/ACCESS-OM3/commit/e6ae976d6d2ed2078b801192ad79b2dea1be1407)

Using model-config-tests (@7670f572f1ec3cc3198ebd5b62e7905a2579c5aa) I tried the following

checkout MOM6-CICE6, 1deg_jra55do_ryf (@070493071c807e26071062ed14be795f150426de)
(COSIMA binary, "access-om3-69f719964a27e23deae3923d60af01a081cc3fc0_main-fkzzqnp")

- model-config-test -m checksum = passes (after setting initial checksum)
- model-config-test -m checksum_slow = passes

changed binary to 

access-om3-git.2024.04.0_2024.04.0-ut3rlqfs7kapqgn6ksnf75ysbfgchi4k from access-nri build

 - model-config-test -m checksum = fail (checksums have changed - no surprise)

copy new checksum to testing/checksum

 - model-config-tests -m "checksum or checksum_slow" = passes

git switch back to spack-packages@main

```
spack uninstall --dependents esmf
spack concretise -f 
spack install
```

changed binary to new build (access-om3-git.2024.04.0_2024.04.0-wiv6b2ibiwurjkghhactrpauzcmjmyx5)

- model-config-test -m checksum = passes
- model-config-test -m checksum_slow = passes

Based on https://github.com/COSIMA/access-om3/issues/40, I expected the runs without this PR (i.e. spack-packages@main) to fail the checksum test. Any thoughts @micaeljtoliveira @dougiesquire ?

Maybe I didn't build properly? Maybe the test doesn't cover how the bfb repro issue was identified initially?

**Comment by anton-seaice** [comment]
I ran the 1deg_jra55do_ryf twice for one day runs, using the build without this change. The md5sum of the cice & mom6 restart files and the diff the restart files from the two runs show they are identical. So i basically I can't reproduce the original problem. I wonder if it go fixed somewhere else unrelated to setting this flag?

**Pull request merged**
