### PR TITLE
mom5: add new variant "type"

### PR DESCRIPTION
**Pull request by harshula**
* "type" will have options ACCESS-CM, ACCESS-OM, ACCESS-ESM, ACCESS-OM-BGC and MOM_solo.

### CODE REVIEW

**Comment by harshula** [comment]
Successfully built, in a docker image, type variants:
```
# spack install mom5 %intel@2021.2.0
# spack install mom5 type=MOM_solo %intel@2021.2.0
# spack install mom5 type=ACCESS-OM-BGC %intel@2021.2.0
```
Please note the following warning:
```
==> Warning: Module file /opt/release/modules/linux-rocky8-x86_64/mom5/master exists and will not be overwritten
```
We many need to include non-default variant names in the module name.

**Comment by harshula** [comment]
Fixes https://github.com/ACCESS-NRI/spack-packages/issues/71

**Comment by harshula** [comment]
On a Gadi login node:
```
$ spack install mom5 type=MOM_solo ^netcdf-c@4.7.4 ^netcdf-fortran@4.5.2  ^openmpi@4.0.2 %intel@19.0.5.281
...
ifort: error #10106: Fatal error in /apps/intel/compilers_and_libraries_2019.5.281/linux/bin/intel64/fortcom, terminated by kill signal
compilation aborted for /scratch/tm70/hj1810/tmp/spack-stage/spack-stage-mom5-master-c4myjhoeotsku627d4pfvaurluscrwrr/spack-src/src/ocean_shared/generic_tracers/generic_miniBLING.F90 (code 1)
make: *** [Makefile:107: generic_miniBLING.o] Error 1
make: *** Waiting for unfinished jobs....
Make failed to create lib_ocean.a
```
This appears to be Gadi killing the process for some reason.

**Comment by harshula** [comment]
Hi @aidanheerdegen , If you could review this ASAP, then I can merge it. Or do want to use this PR to test the CD? The Gadi build failure with type `MOM_solo` appears to be a problem with the Gadi login node, not the SPD, and may go away on another node (e.g. compute node) or after a reboot. I would rather keep `MOM_solo` and note that it is a Gadi problem.

**Comment by aidanheerdegen** [comment]
> If you could review this ASAP, then I can merge it

Sorry, didn't get a chance today. Will prioritise for tomorrow.

Don't need it for CD testing.

**Comment by aidanheerdegen** [comment]
Wasted 40 minutes and got errors like this:

``` 
     153    In file included from /usr/include/bits/floatn.h(119),                                                                                             
     154                     from /usr/include/math.h(43),                                                                                                     
     155                     from /apps/intel/compilers_and_libraries_2019.5.281/linux/compiler/include/math.h(177),                                           
     156                     from /scratch/tm70/aph502/tmp/spack-stage/spack-stage-mom5-master-aollz5h3gjqjhb3pkgfkkqqifm75hals/spack-src/src/postprocessing/mp
            pnccombine/mppnccombine.c(108):                                                                                                                    
  >> 157    /usr/include/bits/floatn-common.h(214): error: invalid combination of type specifiers                                                               
     158      typedef float _Float32; 
...
```

Because I was using the `conda` environment python and it must have some other include paths set. It was picking up incompatible definitions of `float`
```
$ grep 'typedef float' /usr/include/math.h | grep typedef
typedef float float_t;
$ grep 'typedef float'  /usr/include/bits/floatn-common.h
typedef float _Float16 __attribute__ ((__mode__ (__HF__)));
typedef float _Float32;
```

This is just FYI for anyone else in the future, or me when I forget this.

**Comment by aidanheerdegen** [comment]
So BGC build works for me on `gadi`
```
$ spack install mom5 type=ACCESS-OM-BGC ^netcdf-c@4.7.4 ^netcdf-fortran@4.5.2  ^openmpi@4.0.2 %intel@19.0.5.281
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/datetime-fortran-1.7.0-aretozixwsdz42owabgzeiuxooyxrspg                       
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/json-fortran-8.3.0-nyxvikkez6fu64xtbeqqz2a4wngikfgi
==> openmpi@4.0.2 : has external module in ['openmpi/4.0.2']                                                      
[+] /apps/openmpi/4.0.2 (external openmpi-4.0.2-4jwtg3nt7p3zsod4rvn3i3jyyop3arpe)                                    
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/pkgconf-1.9.5-uyq7tvpnuuo3gosnplkvuxktaeeipuqk                                
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/zlib-1.2.13-arj4bfz33zf63gvfionhorrrveci6kb4
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/hdf5-1.14.1-2-a6mpuk7tw5e4pyukxwalooc7jfldalcf
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/netcdf-c-4.7.4-i3inxzaihefr3rqljoovhyevwai6bsff
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/netcdf-fortran-4.5.2-mnx4gghyb5gngsl3fgosud6k72yu2u6a                         
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/oasis3-mct-master-kv5jbt5qltp2kymqka5joksqbatdzspp
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/libaccessom2-master-ajlvl3kyjim4eccn3onqvfp2dvjgyupv
==> Installing mom5-master-aollz5h3gjqjhb3pkgfkkqqifm75hals                           
==> No binary for mom5-master-aollz5h3gjqjhb3pkgfkkqqifm75hals found: installing from source                                                                   
==> No patches needed for mom5                                                                         
==> mom5: Executing phase: 'edit'                                                                                
==> mom5: Executing phase: 'build'                                                               
==> mom5: Executing phase: 'install'                                                                                                                            
==> Warning: Module file /g/data/tm70/aph502/spack-build/release/modules/linux-rocky8-x86_64/mom5/master exists and will not be overwritten                    
==> mom5: Successfully installed mom5-master-aollz5h3gjqjhb3pkgfkkqqifm75hals                                                                                  
  Stage: 7.56s.  Edit: 0.08s.  Build: 4m 38.26s.  Install: 0.19s.  Post-install: 0.32s.  Total: 4m 48.39s
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-master-aollz5h3gjqjhb3pkgfkkqqifm75hals
```

The build time seems very fast, even though it is just building MOM.

**Review by aidanheerdegen — APPROVED** [review]
LGTM. Sorry it has taken to long for me to review it.

**Comment by aidanheerdegen** [comment]
Weird. Couldn't reproduce the `MOM_solo` error. Let's call that a weird aberration as you suggested it might be.

```
$ spack install mom5 type=MOM_solo ^netcdf-c@4.7.4 ^netcdf-fortran@4.5.2  ^openmpi@4.0.2 %intel@19.0.5.281
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/datetime-fortran-1.7.0-aretozixwsdz42owabgzeiuxooyxrspg
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/json-fortran-8.3.0-nyxvikkez6fu64xtbeqqz2a4wngikfgi
==> openmpi@4.0.2 : has external module in ['openmpi/4.0.2']
[+] /apps/openmpi/4.0.2 (external openmpi-4.0.2-4jwtg3nt7p3zsod4rvn3i3jyyop3arpe)
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/pkgconf-1.9.5-uyq7tvpnuuo3gosnplkvuxktaeeipuqk
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/zlib-1.2.13-arj4bfz33zf63gvfionhorrrveci6kb4
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/hdf5-1.14.1-2-a6mpuk7tw5e4pyukxwalooc7jfldalcf
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/netcdf-c-4.7.4-i3inxzaihefr3rqljoovhyevwai6bsff
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/netcdf-fortran-4.5.2-mnx4gghyb5gngsl3fgosud6k72yu2u6a
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/oasis3-mct-master-kv5jbt5qltp2kymqka5joksqbatdzspp
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/libaccessom2-master-ajlvl3kyjim4eccn3onqvfp2dvjgyupv
==> Installing mom5-master-4jfyunr427g3rk667hcyir7xrfytlqoo
==> No binary for mom5-master-4jfyunr427g3rk667hcyir7xrfytlqoo found: installing from source
==> No patches needed for mom5
==> mom5: Executing phase: 'edit'
==> mom5: Executing phase: 'build'
==> mom5: Executing phase: 'install'
==> Warning: Module file /g/data/tm70/aph502/spack-build/release/modules/linux-rocky8-x86_64/mom5/master exists and will not be overwritten
==> mom5: Successfully installed mom5-master-4jfyunr427g3rk667hcyir7xrfytlqoo
  Stage: 6.55s.  Edit: 0.06s.  Build: 8m 4.44s.  Install: 0.50s.  Post-install: 0.53s.  Total: 8m 13.89s
[+] /g/data/tm70/aph502/spack-build/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-master-4jfyunr427g3rk667hcyir7xrfytlqoo
```

**Pull request merged**
